//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarritoItem
    {
        public int id_item { get; set; }
        public int id_carrito { get; set; }
        public int id_vehiculo { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_fin { get; set; }
        public decimal subtotal { get; set; }
    
        public virtual Carrito Carrito { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
