//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hold
    {
        public int id_hold { get; set; }
        public int id_usuario { get; set; }
        public int id_vehiculo { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public System.DateTime fecha_expiracion { get; set; }
        public decimal monto_bloqueado { get; set; }
        public string referencia_banco { get; set; }
        public string estado { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
