//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagenVehiculo
    {
        public int id_imagen { get; set; }
        public int id_vehiculo { get; set; }
        public string uri_imagen { get; set; }
    
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
