//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehiculo()
        {
            this.CarritoItem = new HashSet<CarritoItem>();
            this.Hold = new HashSet<Hold>();
            this.ImagenVehiculo = new HashSet<ImagenVehiculo>();
            this.Reserva = new HashSet<Reserva>();
        }
    
        public int id_vehiculo { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public int anio { get; set; }
        public int id_categoria { get; set; }
        public string transmision { get; set; }
        public Nullable<int> capacidad { get; set; }
        public decimal precio_dia { get; set; }
        public string estado { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> id_sucursal { get; set; }
        public Nullable<int> id_transmision { get; set; }
        public string matricula { get; set; }
        public Nullable<int> id_promocion { get; set; }
        public decimal precio_normal { get; set; }
        public Nullable<decimal> precio_actual { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarritoItem> CarritoItem { get; set; }
        public virtual CategoriaVehiculo CategoriaVehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hold> Hold { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImagenVehiculo> ImagenVehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserva> Reserva { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual TipoTransmision TipoTransmision { get; set; }
        public virtual Promocion Promocion { get; set; }
    }
}
